#include "pch.h"
#include "Nest2D_FreeSpaceEvaluator.h"
#include "Nest2D_SelfFunction.h"
#include <algorithm>
#include <cmath>
namespace ET { namespace NEST2DMANAGERLIB {
CetFreeSpaceEvaluator::CetFreeSpaceEvaluator() : CetCoreObject() {}
CetFreeSpaceEvaluator::~CetFreeSpaceEvaluator() {}
void CetFreeSpaceEvaluator::EvaluateBoardFreeRegionMetrics(const CetTNestItemVector& Items,const TetNestOptions& O,TetTNestEvalResult& R){R.HasBoardFreeRegionMetric=false;R.BoardFreeRegionCount=0;R.LargestFreeRegionArea=0;R.FragmentedFreeArea=0;ClipperLib::Paths Board;if(!Nest2DUtils->Nest2DBord->BuildBoardSubjectContours(O,Board))return;for(std::size_t B=0;B<R.Layers;++B){ClipperLib::Paths Res;if(!Nest2DUtils->Nest2DBord->BuildPlacedReservedContours(Items,(int)B,O.Spacing,Res))return;ClipperLib::Clipper D;if(!D.AddPaths(Board,ClipperLib::ptSubject,true)||(!Res.empty()&&!D.AddPaths(Res,ClipperLib::ptClip,true)))return;ClipperLib::PolyTree T;if(!D.Execute(ClipperLib::ctDifference,T,ClipperLib::pftNonZero,ClipperLib::pftNonZero))return;std::size_t C=0;double Total=0,Largest=0;for(const auto* N:T.Childs)if(N)Nest2DUtils->Nest2DGeometryUtils->AccumulateFreeRegions(*N,C,Total,Largest);R.HasBoardFreeRegionMetric=R.HasBoardFreeRegionMetric||C>0;R.BoardFreeRegionCount+=C;R.LargestFreeRegionArea+=Largest;R.FragmentedFreeArea+=std::max(0.0,Total-Largest);}}
void CetFreeSpaceEvaluator::EvaluatePassableFreeRegionMetrics(const CetTNestItemVector& Items,const TetNestOptions& O,TetTNestEvalResult& R){R.HasPassableFreeRegionMetric=false;R.PassableFreeRegionCount=0;R.LargestPassableFreeRegionArea=0;R.FragmentedPassableFreeArea=0;R.MinimumPassableWidth=Nest2DUtils->Nest2DGeometryUtils->GetMinimumPassableWidth(Items,O);if(R.MinimumPassableWidth<=0)return;ClipperLib::Paths Board;if(!Nest2DUtils->Nest2DBord->BuildBoardSubjectContours(O,Board))return;auto Allow=(libnest2d::Coord)std::ceil(R.MinimumPassableWidth*0.5);ClipperLib::Paths Available;if(!Nest2DUtils->Nest2DGeometryUtils->BuildInsetBoardContours(Board,Allow,Available))return;for(std::size_t B=0;B<R.Layers;++B){ClipperLib::Paths Res;if(!Nest2DUtils->Nest2DBord->BuildPlacedReservedContours(Items,(int)B,O.Spacing,Res,Allow))return;ClipperLib::Clipper D;if(!D.AddPaths(Available,ClipperLib::ptSubject,true)||(!Res.empty()&&!D.AddPaths(Res,ClipperLib::ptClip,true)))return;ClipperLib::PolyTree T;if(!D.Execute(ClipperLib::ctDifference,T,ClipperLib::pftNonZero,ClipperLib::pftNonZero))return;std::size_t C=0;double Total=0,Largest=0;for(const auto* N:T.Childs)if(N)Nest2DUtils->Nest2DGeometryUtils->AccumulateFreeRegions(*N,C,Total,Largest);R.HasPassableFreeRegionMetric=R.HasPassableFreeRegionMetric||C>0;R.PassableFreeRegionCount+=C;R.LargestPassableFreeRegionArea+=Largest;R.FragmentedPassableFreeArea+=std::max(0.0,Total-Largest);}}
bool CetFreeSpaceEvaluator::PreservesPassableFreeSpace(const TetTNestEvalResult& C,const TetTNestEvalResult& B){if(!C.HasPassableFreeRegionMetric||!B.HasPassableFreeRegionMetric)return true;double T=std::max({1.0,std::abs(C.LargestPassableFreeRegionArea),std::abs(B.LargestPassableFreeRegionArea)})*1e-9;return C.FragmentedPassableFreeArea<=B.FragmentedPassableFreeArea+T&&C.LargestPassableFreeRegionArea+T>=B.LargestPassableFreeRegionArea&&C.PassableFreeRegionCount<=B.PassableFreeRegionCount;}
bool CetFreeSpaceEvaluator::IsBetterContinuousFreeSpace(const TetTNestEvalResult& C,const TetTNestEvalResult& B){bool P=C.HasPassableFreeRegionMetric&&B.HasPassableFreeRegionMetric;bool G=C.HasBoardFreeRegionMetric&&B.HasBoardFreeRegionMetric;if(!P&&!G)return false;double CA=P?C.LargestPassableFreeRegionArea:C.LargestFreeRegionArea,BA=P?B.LargestPassableFreeRegionArea:B.LargestFreeRegionArea;return CA>=BA+std::max(1.0,std::abs(BA)*0.01);}
}}
