#pragma once


enum MetNest2DErrorCode {

	Nest2D_Success = 0,

	
	NEST2D_ERR_CORE_EMPTY_INPUT = -101, 
	NEST2D_ERR_CORE_INVALID_SIZE = -102, 
	NEST2D_ERR_CORE_NESTING_FAILED = -103, 

	
	NEST2D_ERR_FILE_OPEN_FAILED = -201, 
	NEST2D_ERR_FILE_BIN_FORMAT = -202, 
	NEST2D_ERR_FILE_BIN_SIZE = -203, 
	NEST2D_ERR_FILE_SPACING_FMT = -204, 
	NEST2D_ERR_FILE_SPACING_VAL = -205, 
	NEST2D_ERR_FILE_ROTATIONS_FMT = -206, 
	NEST2D_ERR_FILE_ROTATIONS_VAL = -207, 
	NEST2D_ERR_FILE_POLY_FMT = -208, 
	NEST2D_ERR_FILE_POLY_PTS_FEW = -209, 
	NEST2D_ERR_FILE_POLY_COORD_FMT = -210, 
	NEST2D_ERR_FILE_POLY_COORD_INF = -211, 
	NEST2D_ERR_FILE_HOLE_NO_POLY = -212, 
	NEST2D_ERR_FILE_HOLE_FMT = -213, 
	NEST2D_ERR_FILE_HOLE_PTS_FEW = -214, 
	NEST2D_ERR_FILE_HOLE_COORD_FMT = -215, 
	NEST2D_ERR_FILE_HOLE_COORD_INF = -216, 
	NEST2D_ERR_FILE_UNKNOWN_TOKEN = -217, 
	NEST2D_ERR_FILE_NO_POLYGON = -218, 
	NEST2D_ERR_FILE_MISSING_BIN = -219, 

	
	NEST2D_ERR_EXPORT_EMPTY_ITEMS = -301, 
	NEST2D_ERR_EXPORT_NO_PATH = -302  
};