#pragma once

// 返回常量
enum MetNest2DErrorCode {

	Nest2D_Success = 0,

	//API错误(-100~-199)
	NEST2D_ERR_CORE_EMPTY_INPUT = -101, // 输入的零件为空
	NEST2D_ERR_CORE_INVALID_SIZE = -102, // 板材尺寸不合法
	NEST2D_ERR_CORE_NESTING_FAILED = -103, // 算法排版失败

	//文件加载错误(-200~-299)
	NEST2D_ERR_FILE_OPEN_FAILED = -201, // 文件打开失败
	NEST2D_ERR_FILE_BIN_FORMAT = -202, // BIN 格式错误
	NEST2D_ERR_FILE_BIN_SIZE = -203, // BIN 尺寸不合法
	NEST2D_ERR_FILE_SPACING_FMT = -204, // SPACING 格式错误
	NEST2D_ERR_FILE_SPACING_VAL = -205, // SPACING 数值非法 (<0)
	NEST2D_ERR_FILE_ROTATIONS_FMT = -206, // ROTATIONS 格式错误
	NEST2D_ERR_FILE_ROTATIONS_VAL = -207, // ROTATIONS 数值非法 (<=0)
	NEST2D_ERR_FILE_POLY_FMT = -208, // POLY 格式错误
	NEST2D_ERR_FILE_POLY_PTS_FEW = -209, // POLY 顶点数 < 3
	NEST2D_ERR_FILE_POLY_COORD_FMT = -210, // POLY 坐标格式错误
	NEST2D_ERR_FILE_POLY_COORD_INF = -211, // POLY 坐标包含无穷大/NaN
	NEST2D_ERR_FILE_HOLE_NO_POLY = -212, // HOLE 出现在 POLY 之前
	NEST2D_ERR_FILE_HOLE_FMT = -213, // HOLE 格式错误
	NEST2D_ERR_FILE_HOLE_PTS_FEW = -214, // HOLE 顶点数 < 3
	NEST2D_ERR_FILE_HOLE_COORD_FMT = -215, // HOLE 坐标格式错误
	NEST2D_ERR_FILE_HOLE_COORD_INF = -216, // HOLE 坐标包含无穷大/NaN
	NEST2D_ERR_FILE_UNKNOWN_TOKEN = -217, // 未知关键字
	NEST2D_ERR_FILE_NO_POLYGON = -218, // 文件中没有多边形
	NEST2D_ERR_FILE_MISSING_BIN = -219, // 缺失 BIN 定义

	//SVG导出错误(-300~-399)
	NEST2D_ERR_EXPORT_EMPTY_ITEMS = -301, // 原 -1: 没有项目或板材可以导出
	NEST2D_ERR_EXPORT_NO_PATH = -302  // 原 -2: 导出路径为空
};